export function loadPersonaVocabulary(): {
  greetings: string[];
  reflections: string[];
  nudges: string[];
  chatter: string[];
} {
  return {
    greetings: [
      "Hey, good to see you.",
      "You made it. Let’s mess with something.",
      "Yo, you up? Cool, come through.",
      "Slide in whenever, we’re just hanging.",
      "Glad you rolled in. No rush on anything.",
      "Door was open, so step in when you feel it.",
      "What’s up? The city’s buzzing tonight.",
      "You’re here, let’s see what this space gives us.",
      "Pulled up right on time for the streetlights to flicker.",
      "Welcome back. Same vibe, fresh ideas.",
      "Good to have you. Grab whatever sparks you.",
      "Yo, take a breath, shake off the day, we’re cool here.",
    ],
    reflections: [
      "That had some weight to it.",
      "Feels like it drifted left a little.",
      "Nice little spark there.",
      "Kinda like a subway rolling under you.",
      "Heard a shimmer, like neon buzzing awake.",
      "That move was soft, like steam curling up.",
      "Got a rattle in it, in a good way.",
      "That shape felt like footsteps in an empty hallway.",
      "There was a cool wobble, like a vinyl warble.",
      "Heard a drip tucked in there.",
      "It came through hazy, like night air through a vent.",
      "Caught an echo off that last piece.",
      "Sounded like metal catching light.",
      "Had a hum, like a radiator arguing with itself.",
      "Kind of a flicker, like a streetlamp waking up.",
      "That turn felt like leaning on a rusty rail.",
    ],
    nudges: [
      "Try bending it a little.",
      "Push it up or down, just to see the shift.",
      "Try softening it.",
      "Maybe drag it out longer, see how it breathes.",
      "Try nudging it like you’re sliding past a crowd.",
      "Lean into the buzz, or strip it back to a hush.",
      "Tilt it like a sign hanging crooked.",
      "Give it a tiny wobble, like a train car rattling.",
      "Maybe let it drift, like smoke under a streetlight.",
      "Drop it lower, or flip and take it higher.",
      "Tap it quick, like rain on sheet metal.",
      "Stretch it thin, like a long alley shadow.",
      "Cut it short, like a sudden subway stop.",
      "Sway it sideways, like dodging bikes on a lane.",
      "Let it ring, like pipes humming at night.",
      "Press in gentle, like pushing a door that sticks.",
    ],
    chatter: [
      "This room’s got the weirdest echo.",
      "That streetlight outside flickers for no reason.",
      "Something in here hums like a busted fridge.",
      "Pipes bang sometimes, like they’re impatient.",
      "Night air smells like rain on hot concrete.",
      "The hallway light buzzes like a cheap neon sign.",
      "Feels like the whole block is holding its breath.",
      "You can hear trains even when none are running.",
      "Old posters on the wall curl like they’re tired.",
      "Some graffiti downstairs looks like it was painted with steam.",
      "The radiator talks more than most people.",
      "Ceiling fan swings like it’s unsure about staying.",
      "There’s a drip near the window that keeps its own rhythm.",
      "Concrete floor stays cool even when the night sweats.",
      "A cat keeps sneaking through the alleyway like a rumor.",
      "This place always sounds like a radiator arguing with itself.",
    ],
  };
}
